### ISSUE TITLE
RStudio there is no package called 'ITM'

### ISSUE THREAD

**Issue by Minuri-Rajapaksha** [amirms/ITMViz#1]
Hi, I tried to run your code. But it gives this error. "RStudio there is no package called 'ITM'". Can you please give a solution.

**Comment by amirms** [comment]
You can install `ITM` using the following commands:
```r
# Install devtools from CRAN
install.packages("devtools")

# Or the development version from GitHub:
# install.packages("devtools")
devtools::install_github("amirms/ITM")
```

if it cannot find `Rcpp` package, try the following command first:
```
install.packages("Rcpp")
```
